language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

branches:
  only:
    - staging
    - master

before_script:
  - npm install

script:
  - if [[ "$TRAVIS_BRANCH" = "master" || "$TRAVIS_BRANCH" = "staging" ]]; then npm run build --prod; else echo "not a build branch"; fi

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - sed -i '/dist/d' .gitignore
  - git add . && git commit -m "latest build"

deploy:
  - provider: elasticbeanstalk
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    region: "ap-south-1"
    app: "traverse_angular"
    env: "traversepk"
    bucket_name: "elasticbeanstalk-ap-south-1-202999161102"
    on:
      branch: master

after_deploy:
  - echo "Applcation Deployed!"
